server:
  port: 8762
spring:
  application:
    name: torrent-download-service
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          min-partition-count: 1
      bindings:
        download-message-in:
          group: torrent-download-group
          destination: downloadMessages
          contentType: application/json
        torrent-message-out:
          destination: torrentMessages
          contentType: application/json
          producer:
            compressionType: gzip
        index-message-out:
          destination: indexMessages
          contentType: application/json
          producer:
            compressionType: gzip
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  httpclient:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

download:
  num:
    thread: 500